# Generated by Django 3.2.3 on 2021-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kickrani',
            fields=[
                ('kickId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=250)),
                ('violation', models.IntegerField(default=0, null=True)),
                ('violationImg', models.CharField(max_length=250, null=True)),
                ('kickDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
