# Generated by Django 3.2.3 on 2021-05-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kickrani',
            old_name='kickDate',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='kickrani',
            old_name='violationImg',
            new_name='image',
        ),
        migrations.AddField(
            model_name='kickrani',
            name='helmet',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='kickrani',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='kickrani',
            name='person',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
