# Generated by Django 3.2.3 on 2021-06-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('datetime', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('rider_number', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('rider_ID', models.AutoField(primary_key=True, serialize=False)),
                ('rider_location', models.CharField(max_length=250, null=True)),
                ('rider_percentage', models.FloatField(max_length=250, null=True)),
                ('brand', models.CharField(max_length=250, null=True)),
                ('helmet_number', models.IntegerField(default=0, null=True)),
                ('person_number', models.IntegerField(default=0, null=True)),
                ('foul', models.IntegerField(default=0, null=True)),
                ('datetime', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('num_brand', models.IntegerField(default=0, null=True)),
                ('image_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.image')),
            ],
        ),
        migrations.CreateModel(
            name='Rider_information',
            fields=[
                ('information_Id', models.AutoField(primary_key=True, serialize=False)),
                ('helmet_location', models.CharField(max_length=250, null=True)),
                ('helmet_percentage', models.FloatField(max_length=250, null=True)),
                ('person_location', models.CharField(max_length=250, null=True)),
                ('person_percentage', models.FloatField(max_length=250, null=True)),
                ('rider_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rider')),
            ],
        ),
        migrations.DeleteModel(
            name='Kickrani',
        ),
    ]
