# Generated by Django 3.2 on 2021-05-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210522_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickrani',
            name='brand',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kickrani',
            name='datetime',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
