# Generated by Django 3.2.3 on 2021-06-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rider_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickrani',
            name='num_brand',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
